### ISSUE TITLE
23.09.07 일정

### ISSUE THREAD

**Issue by KMGeon** [KMGeon/Aswemake#1]
### 23.09.06까지
- 요구사항 API 완료
- 테스트 코드 부분 작성

### Todo : 일정
- [ ] 변수, 함수명 명확하게 리펙토링 하기
- [x] Exception 처리 제대로 하기
- [x] 주석으로 API 설명하기
- [x] Security Config  권한 추가된거 설정하기
- [x] 남은 기간동안 TDD 방식으로 기능 추가 및 리펙토링
- [x] Fetch Join, Batch Size 분리
- [x] 관심사에 맞는 코드 리펙토링
- [x] 결제를 하였을 때 수량 제거
- [x] 쿠폰을 사용하면 false로
- [x] bulk update 최적화

### 시간 남으면 해볼거
- [ ] enum convert 한번 사용하기
- [ ] Service Layer 테스트 코드 리펙토링 해보기 -> 더 좋은 방식이 없나.
- [ ] 관련 로직 Domain에서 한번 리펙토링 해보기
- [ ] 배달 위도, 경도로 설정해서 추가하기
